#!/bin/bash

mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps && cp $APPDIR/PPSSPP.svg $HOME/.local/share/icons/hicolor/scalable/apps

GITVER=$(wget -qO- https://www.github.com/qurious-pixel/PPSSPP/releases/tag/continuous | grep -o -P 'runs/[0-9]*' | cut -d '/' -f 2 | awk '!x[$0]++') 
APPVER=$(cat $APPDIR/version.txt)

if [[ -z "$GITVER" ]]; then
	$APPDIR/AppRun-patched 
elif [ "$GITVER" = "$APPVER" ]; then
	$APPDIR/AppRun-patched 
else
	$APPDIR/update.sh
fi
