# https://travis-ci.org

language: cpp

os: linux
dist: xenial

addons:
  apt:
    update: true
    packages:
      - ant
      - aria2
      - build-essential
      - cmake
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - p7zip-full
      - pv
      - software-properties-common
    sources:
      - sourceline: 'ppa:zoogie/sdl2-snapshots'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
  homebrew:
    update: true
    packages:
      - ccache
      - sdl2

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/clcache



jobs:
  include:
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
   
before_install:
  - travis_retry bash .travis.sh travis_before_install

install:
  - travis_retry bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script
  - mkdir artifacts/
  - cp build/PPSSPPSDL artifacts/
  - 7z a assets.zip build/assets 
  - cp build/assets.zip artifacts/
  - ls -al build/
after_success: 
  - ls -al artifacts/
  - wget -c https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
  - tar xfv ghr_v0.13.0_linux_amd64.tar.gz
  - ghr_v0.13.0_linux_amd64/ghr -recreate -n 'Continous build' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/
branches: 
  except: 
    - /^(?i:continuous.*)$/
deploy: 
  api_key: $GITHUB_TOKEN
  file: artifacts/*
  file_glob: true
  provider: releases
  skip_cleanup: true
  true: 
    tags: true
